### ISSUE TITLE
屏幕卡住，多个软件界面重叠卡死

### ISSUE THREAD

**Issue by shawnl111** [bavelee/Asus_X550VQ-Hackintosh#1]
您好，我使用的是您的efi，但是每次开机之后过一会就会突然卡死，如下图。请问您有联系方式吗，可以加一下探讨下嘛。
![IMG_20210616_180659](https://user-images.githubusercontent.com/38712239/122227638-eabcdb00-ce6b-11eb-80f6-8fec7985d19a.jpg)

**Comment by shawnl111** [comment]
对了，如果开机时，连接了hdmi输出另外一个显示器，则会一直黑屏。

**Comment by z0brk** [comment]
这是我朋友的机器，在他的机器上一切正常，我发出来只做分享，请自行寻找解决办法。
